version: 2.1
jobs:
  build:
    steps:
      - checkout
      
      - run:
          name: Dependencias
          command: bundle install
      
      - run:
          name: Compilar el sitio
          command: bundle exec jekyll build
